N = 4 <br>
prototype

<h4>Item <i>"a)"</i> Onde f = 0 e u(x,y)= alpha * np.exp(x) * np.sin(y) na fronteira</h4>

In [1]:
import numpy as np
from time import time

In [ ]:
N=3
MAXITER=10**3

alpha = 3.0
h=1./N

TOL = 10**-5 * h

<h3>Funções Auxiliares</h3>

<h4>Jacobi</h4>

In [ ]:
def jacobi_method(U_old, U_new, h, F):
    for i in range(1,N):
        for j in range(1,N):
            U_new[i][j] = 0.25*(U_old[i-1][j] + U_old[i+1][j] + U_old[i][j-1] + U_old[i][j+1] + h**2 * F[i][j])


<h4>PASSO 1 e 2</h4>

In [ ]:
U_old = np.zeros((N+1,N+1))
U_new = np.zeros((N+1,N+1))
F = np.zeros((N+1,N+1)) 

<h4>PASSO 3</h4>

In [ ]:
F = np.zeros((N+1,N+1)) 

<h4>PASSO 4</h4>

In [ ]:
# Atualiza as bordas


# Parte inferior e superior da Malha
for i in range(N+1):
    U_old[i, 0] = alpha * np.exp(h*i) * np.sin(h*0.)
    U_old[i, N] = alpha * np.exp(h*i) * np.sin(h*N)

# Parte esquerda e direita da Malha
for j in range(N+1):
    U_old[0, j] = alpha * np.exp(h*0.) * np.sin(h*j)
    U_old[N, j] = alpha * np.exp(h*N) * np.sin(h*j)    


In [ ]:
U_old

<h4>PASSO 5-7</h4>

In [ ]:
for it in range(MAXITER):
    jacobi_method(U_old, U_new, h, F)
    
#     if calculate_diff(U_new, U_old) <= TOL:
#         print('Algoritmo convergiu com %d iterações' %(it))
#         break
    
    U_old = U_new.copy()

In [ ]:
U_new

<h2>Item B</h2>

In [12]:
N=3
MAXITER=10**3

alpha = 3.0
h=1./N

TOL = 10**-5 * h

In [22]:
U_old = np.zeros((N+1,N+1))
U_new = np.zeros((N+1,N+1))
F = np.zeros((N+1,N+1)) 

In [14]:
def initialize_F_matrix(F, N):
    for j_y in range(N+1):
        for i_x in range(N+1):
            F[i_x, j_y] = round(6. * np.pi**2 * np.cos(np.pi * (i_x*h)) * np.sin(np.pi * (j_y*h)) , 2) 
            
    return F

In [21]:
def initialize_U_edges(U_old, N):
    # Parte inferior e superior da Malha
    for i_x in range(N+1):
        U_old[i_x, 0] = round(3. * np.cos(np.pi * (h*i_x)) * np.sin(np.pi * (h*0.)), 2)
        U_old[i_x, N] = round(3. * np.cos(np.pi * (h*i_x)) * np.sin(np.pi * (h*N )), 2)

    # Parte esquerda e direita da Malha
    for j_y in range(N+1):
        U_old[0, j_y] = round(3. * np.cos(np.pi * (h*0.)) * np.sin(np.pi * (h*j_y)), 2)
        U_old[N, j_y] = round(3. * np.cos(np.pi * (h*N) ) * np.sin(np.pi * (h*j_y)), 2)
    
    return U_old


In [23]:
F = initialize_F_matrix(F, N)
U_old = initialize_U_edges(U_old, N)

In [24]:
F

array([[  0.  ,  51.28,  51.28,   0.  ],
       [  0.  ,  25.64,  25.64,   0.  ],
       [ -0.  , -25.64, -25.64,  -0.  ],
       [ -0.  , -51.28, -51.28,  -0.  ]])

In [25]:
U_old

array([[ 0. ,  2.6,  2.6,  0. ],
       [ 0. ,  0. ,  0. ,  0. ],
       [-0. ,  0. ,  0. , -0. ],
       [-0. , -2.6, -2.6, -0. ]])

In [54]:
np.array([[  0.  ,  51.28,  51.28,   0.  ],
       [  0.  ,  25.64,  25.64,   0.  ],
       [ -0.  , -25.64, -25.64,  -0.  ],
       [ -0.  , -51.28, -51.28,  -0.  ]])

array([[  0.  ,  51.28,  51.28,   0.  ],
       [  0.  ,  25.64,  25.64,   0.  ],
       [ -0.  , -25.64, -25.64,  -0.  ],
       [ -0.  , -51.28, -51.28,  -0.  ]])